name: 'deploy-be-heroku' # set whatever name you want to your github job
on: [workflow_dispatch]  # set the events you would like to trigger this job
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ice-cream-logistics
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Herokup
        id: heroku
        uses: lucassarcanjo/heroku-deploy@2.1.17
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          api_key: ${{ secrets.HEROKU_API_KEY }}
          app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_path: "/IceCreamLogistics/IceCreamLogisticsBackEnd/Dockerfile"
