name: Frontend Deploy to Gh Pages
on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: All things angular
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.2 ## replace by latest version without it you will see Expected format {org}/{repo}[/path]@ref. Actual 'AhsanAyaz/angular-deploy-gh-pages-actions',Input string was not in a correct format.
      with:
        github_access_token: ${{ secrets.ACCESS_TOKEN }} # see the Configuration section for how you can create secrets
        angular_project_dir: IceCreamLogisticsApp
        build_configuration: production # The build environment for the app. please look configurations in your angular.json
        base_href: /IceCreamLogistics/   # make sure this corresponds to https://<your_username>.github.io/<base_href>/
        deploy_branch: main # The branch the action should deploy to.
